elasticjob: 
  zk: 
    serverList: 10.106.0.90:2181
    namespace: jason_elastic_job
  datasource:
    druid: 
      url: jdbc:mysql://127.0.0.1:3306/elastic_job?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver